### ISSUE TITLE
مولتی سرور 

### ISSUE THREAD

**Issue by KanekiDevPro** [Azumi67/Haproxy_TCP_loadbalance#2]
سلام وقتتون بخیر امکانش هست یه ایران رو به دوتا خارج با این روش تانل زد ؟ و اینکه میتونه پهنای باند بالا رو هندل کنه ؟ پیشنهاد خودتون چیه ؟

**Comment by Azumi67** [comment]
سلام بله . Haproxy خیلی خوبه .

**Comment by KanekiDevPro** [comment]
لود بالانس -سرور ایران - تانل - با استفاده از پرایوت ایپی با این روش میشه ؟ یا گزینه دیگه ایه ؟
