### ISSUE TITLE
اپدیت

### ISSUE THREAD

**Issue by KanekiDevPro** [Azumi67/Haproxy_TCP_loadbalance#3]
سلام وقت بخیر ممنون بابت این اسکریپ خوبتون کار رو راحت کرده فقط دوتا پیشنهاد داشتم اگه امکانش باشه یکی اینه که مولتی سرور رو اوکی کنید و دومی هم اپدیتی برای این اسکریپت نمیاد دیگه ؟

**Comment by Azumi67** [comment]
سلام. الان دارم چند روش دیگر اضافه میکنم . اگر موردی دوست دارید بهش اضافه بشه بهم بگید ببینم میتونم اضافه کنم یا خیر.

**Comment by KanekiDevPro** [comment]
ریست تایمر میتونه گزینه خوبی باشه و اینکه حتما مولتی سرور اضافه بشه عالی میشه یه ایران رو به دوتا یا چند تا خارج با پورت های مختلف تانل زد مثل گوست ممنون از شما :)

**Comment by Hsngh01** [comment]
سلام در ابونتو ۲۴ اسکریپت تانل haporoxy کار نمیکنه

**Comment by Azumi67** [comment]
> سلام در ابونتو ۲۴ اسکریپت تانل haporoxy کار نمیکنه

سلام. باشه یک آپدیت برای این موضوع خواهم داد

**Comment by KanekiDevPro** [comment]
مولتی سرور رو حتما اضافه کنید مثل 1 ایران و چند خارج و برعکس :)

**Comment by Azumi67** [comment]
> مولتی سرور رو حتما اضافه کنید مثل 1 ایران و چند خارج و برعکس :)

بذارید کارهای پنل تموم بشه، این پروژه رو آپدیت میکنم .
